name: CI and CD
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn package --batch-mode -DskipTests
      - name: Test with Maven
        run: mvn verify
      - name: Build docker and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: 'paschoalini'
          password: ${{ secrets.DOCKER_PAT }}
          repository: paschoalini/demo
          tags: ${{ github.sha }}, latest